language: R
warnings_are_errors: false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - name: "TensorFlow (2.0.0)"
      env:
        - TENSORFLOW_VERSION="2.0.0"
      r_github_packages:
        - rstudio/reticulate
        - rstudio/tensorflow

addons:
  apt:
    packages:
      python3-dev
      python3-pip
      python3-virtualenv
      python3-venv
      python3-setuptools

before_script:
  - python3 -m pip install --upgrade --ignore-installed --user travis virtualenv
  - Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')"
  - Rscript -e "remotes::install_github('rstudio/reticulate')"
  - Rscript -e "reticulate::install_miniconda()"
  - Rscript -e "reticulate::conda_create('r-reticulate', packages = c('python==3.6.9'))"
  - R CMD INSTALL .
  - R -e 'tensorflow::install_tensorflow(version = Sys.getenv("TENSORFLOW_VERSION"))'
  - Rscript -e "reticulate::py_install('IPython', pip = TRUE)"
  - R -e 'tensorflow::tf_config()'
